### ISSUE TITLE
flutter doctor unsupport os: android

### ISSUE THREAD

**Issue by ANIL80531** [lycstar/build_dart_android_arm64_sdk#1]
I saw you post [here](https://github.com/termux/termux-app/issues/1247#issuecomment-774109521).
Can you help me run flutter on termux.
I have managed to run flutter build with dart provided by termux but running flutter doctor gives error unsupport os : android.
Pls help i will be indebted for your help.
![IMG_20220727_225509.jpg](https://user-images.githubusercontent.com/61663725/181312902-e8604d48-d139-45c2-862d-f63f5b4aa88f.jpg)

**Comment by lycstar** [comment]
modify code in flutter_tools to support android host, but only flutter build web commod is useful in termux.



发自我的iPhone


------------------ Original ------------------
From: I AM IRON MAN 80531 ***@***.***&gt;
Date: Thu,Jul 28,2022 1:35 AM
To: lycstar/build_dart_android_arm64_sdk ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [lycstar/build_dart_android_arm64_sdk] flutter doctor unsupport os:android (Issue #1)

**Comment by ANIL80531** [comment]
which file and where I'm learning to code, and will be happy with web only 

![Screenshot_2022-07-27-23-13-28-783_com.termux.jpg](https://user-images.githubusercontent.com/61663725/181315285-6d9d9b47-6165-458b-9bc7-bdb7712bc677.jpg)

**Comment by lycstar** [comment]
sdk/.../packages/flutter_tools，you can search that error(Unsupported operating...)to find file you need to mod.

**Comment by ANIL80531** [comment]
I have commented out all throw error lines in flutter_tools folder but it is still showing same error. 
what should i do?

![IMG_20220728_084201.jpg](https://user-images.githubusercontent.com/61663725/181412486-faf303a4-215c-46c0-bfc9-b3b7e58753d9.jpg)

**Comment by lycstar** [comment]
1.You should add code to support Android host instead of replacing the error output globally, which is meaningless.
2.you need delete sdk\bin\cache\flutter_tools.snapshot and flutter_tools.stamp，then rerun flutter doctor, it will rebuild flutter_tools。Otherwise, your changed code will not take effect

**Comment by ANIL80531** [comment]
can you share your flutter zip for termux

**Comment by lycstar** [comment]
no, I haven't done it for a long time

**Comment by lycstar** [comment]
[flutter_tools.zip](https://github.com/lycstar/build_dart_android_arm64_sdk/files/9205781/flutter_tools.zip)
Here is an old version you can compare.

1. in base/os.dart and build_info.dart
![image](https://user-images.githubusercontent.com/37872392/181430759-9ad29973-3b5c-4f2b-b687-1f405c61bdfd.png)
2.  in build_info.dart
![image](https://user-images.githubusercontent.com/37872392/181431023-8ea91b46-1590-41f6-9e31-9876e2a0cd25.png)
3. in artifacts.dart
![image](https://user-images.githubusercontent.com/37872392/181431123-3325ae0e-e815-436f-9df3-39069a04e045.png)

**Comment by leap0x7b** [comment]
@lycstar i followed your instructions and got this
![Screenshot_20221126-075824_Termux.png](https://user-images.githubusercontent.com/76893443/204066498-97a91657-420c-49ed-aed2-c33e7cca057b.png)

**Comment by lycstar** [comment]
> @lycstar i followed your instructions and got this
> ![Screenshot_20221126-075824_Termux.png](https://user-images.githubusercontent.com/76893443/204066498-97a91657-420c-49ed-aed2-c33e7cca057b.png)

maybe you need rewrite code.

**Comment by leap0x7b** [comment]
What do you mean?

**Comment by ANIL80531** [comment]
Hey, did you solved this issue
[target android_aot_release_android-arm failed #85434](https://github.com/flutter/flutter/issues/85434)
